### ISSUE TITLE
Homepage (index.html) navigation bar can appear better than the current one in mobile screens

### ISSUE THREAD

**Issue by technovisioncs** [technovisioncs/technovisioncs.github.io#10]
![image](https://cloud.githubusercontent.com/assets/23166456/20269474/3bc3124e-aaa9-11e6-94c8-65772b361e1b.png)
as you can see in the above image its appearing fine, but is it possible to make it appear as toggle menu ?
which will make the responsiveness much better . The one which is used with events file will  do or else any other type of toggle menu will also help.
for example like this :

https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjT9__TwqjQAhXJtY8KHdNjAYsQjRwIBw&url=http%3A%2F%2Fjquery-plugins.net%2Ftag%2Ftoggle-menu&psig=AFQjCNH00hcm7bMEzPAxI1HjDWrNQZFkbQ&ust=1479222269281903

**Comment by ghost** [comment]
made a phone menu - check pull req

**Comment by sorinr** [comment]
made some changes in index.tml/style.css/main.js
see the attachement
[changes.zip](https://github.com/technovisioncs/technovisioncs.github.io/files/592064/changes.zip)

**Comment by technovisioncs** [comment]
Thanks a lot sorinr and ryder-rtyrolia

**Comment by sorinr** [comment]
Made some other changes as a proposal for the events section.
Take a look and let me know your opinion.
[changes2.zip](https://github.com/technovisioncs/technovisioncs.github.io/files/592997/changes2.zip)
