### ISSUE TITLE
All Events page are not mobile responsive 

### ISSUE THREAD

**Issue by technovisioncs** [technovisioncs/technovisioncs.github.io#3]
![image](https://cloud.githubusercontent.com/assets/23166456/20247048/d12b0c94-a9e9-11e6-95fd-acd3380765df.png)

here's one sample event page 
its not appearing the way it should be

**Comment by ghost** [comment]
make it mobile responsive by 

meta name="viewport" content="width=device-width, initial-scale=1"

insert <  >

also u can use a media query added to ur css like 

@media screen and(max-width:480px){
  #sidebar{display:none;}
}

or make a responsive.css

**Comment by technovisioncs** [comment]
i already did that , but some part of its hard to analyze

**Comment by profoundhub** [comment]
~ Closed
